### ISSUE TITLE
character spacing

### ISSUE THREAD

**Issue by remcoder** [remcoder/Pxxl.js#3]

**Comment by callebe** [comment]
I'm having some problems with character spacing. I'm trying to print on a canvas the following phrase "The Quick brown fox jumps over the lazy dog", but the spacing between 'i', 'j' and 'l' does not follow the BDF definitions. 

[dms.zip](https://github.com/remcoder/Pxxl.js/files/2472728/dms.zip)

**Comment by remcoder** [comment]
Hi @callebe, how nice that you're using Pxxl.js. I'm not actively maintaining it anymore actually. Though, If you'd want to take the time to make a PR to add support, let me know if I can help.
